version: '{branch}-{build}'

init:
  # Create our AppVeyor version
  - ps: $env:commit = $env:appveyor_repo_commit.SubString(0,7)
  - ps: Update-AppveyorBuild -Version ("{0}-{1}-{2}" -f $env:appveyor_repo_branch,$env:appveyor_build_number,$env:commit )

environment:
  VSVER: 14.0
  matrix:
    - MSVC_VERSION: 15
      RUNTIME_LINKAGE: static
      QT_VERSION: 5.8
      QT_LINKAGE: static
      ICU_VERSION: 57.1
      ICU_LINKAGE: static
      COVERITY_BUILD_CANDIDATE: True
      QTDIR: C:\Qt\5.8\msvc2015
      VCLIBS: VCRUNTIME140.dll MSVCP140.dll

configuration:
  - release

install:
  # Set some vars
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - set VCLIBDIR=%WINDIR%\SysWOW64 # Find vclibs
  - set QTDIR
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

before_build:
  # Prepare the out-of-source build directory.
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - qmake %APPVEYOR_BUILD_FOLDER%/app/rtkuser-qt -o %APPVEYOR_BUILD_FOLDER%-build -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION%

build_script:
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - cd C:\MinGW\bin
  - ls
  - cd "%APPVEYOR_BUILD_FOLDER%\app\convbin\gcc"
  - gcc --version
  - mingw32-make CC=gcc
  - ls
  - copy convbin.exe %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\convbin.exe

  - cd "%APPVEYOR_BUILD_FOLDER%\app\rnx2rtkp\gcc"
  - gcc --version
  - mingw32-make CC=gcc
  - ls
  - copy rnx2rtkp.exe %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\rnx2rtkp.exe

  - cd "%APPVEYOR_BUILD_FOLDER%\app\pos2kml\gcc"
  - gcc --version
  - mingw32-make CC=gcc
  - ls
  - copy pos2kml.exe %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\pos2kml.exe

  - setx INCLUDE "%INCLUDE%;%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\include"
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat"
  - devenv /Upgrade "%APPVEYOR_BUILD_FOLDER%\app\convbin\msc\msc.vcproj"
  #- msbuild "%APPVEYOR_BUILD_FOLDER%\app\convbin\msc\msc.vcxproj" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  #- cd "%APPVEYOR_BUILD_FOLDER%\app\convbin\gcc"
  #- '%make%'
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - '%make%'
  - dir /b /s *.exe

after_build:
  # Add a link to the build output within the source directory. This is needed because AppVeyor does
  # not support extracting artifacts from out-of-source build directories. See 'artifacts' below.
  - dir /b /s *.exe
  - mkdir deploy
  - copy %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\RTKUSER.exe deploy\RTKUSER.exe
  - copy %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\configs.conf deploy\configs.conf
  - copy %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\configs2.conf deploy\configs2.conf
  - copy %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\convbin.exe deploy\convbin.exe
  - copy %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\rnx2rtkp.exe deploy\rnx2rtkp.exe
  - copy %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\pos2kml.exe deploy\pos2kml.exe
  - windeployqt --release deploy/RTKUSER.exe
  #- windeployqt --release deploy/convbin.exe not a qt app
  - for %%I in (%VCLIBS%) do copy %VCLIBDIR%\%%I deploy\
  - 7z a -tzip HORUS_RTKUSER_%commit%.zip deploy -r
  - copy %APPVEYOR_BUILD_FOLDER%-build\HORUS_RTKUSER_%commit%.zip %APPVEYOR_BUILD_FOLDER%\HORUS_RTKUSER_%commit%.zip
  - dir /b /s *.zip

artifacts:
  - path: HORUS_RTKUSER_%commit%.zip
    name: RTKUSER
